name: Run fetch_data_daily.py every 60 minutes

on:
  schedule:
    - cron: '7 * * * *'  # Every 60 minutes (UTC)
  workflow_dispatch:     # Allow manual run via GitHub UI

permissions:
  contents: write  # Allow the action to push changes to the repository

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.12
        uses: actions/setup-python@v3
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run fetch_data_daliy.py
        run: python3 fetch_data_daliy.py

      - name: commit and push to github repository
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add forecast_results.json
          git add results.json
          git commit -m "updated forecast_results.json and results.json by github actions"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/IamMegaNoobb/Airmind_Sight_deploy.git HEAD:main
